added display-type to generated serialized json for attributes
onflow/flow-evm-bridge pull request #128
Opened 2024-10-11 18:14 UTC by bjartek

## Description

The generated json does not include display_type

Sorry for whitespace mod here. lmk if you want me to redo.

2024-10-17 23:03 UTC, sisyphusSmiling commented on cadence/contracts/utils/SerializeMetadata.cdc
> +            .concat(", \"display_type\": ").concat(Serialize.tryToJSONString(trait.display_type)!)
```suggestion
            .concat(", \"display_type\": ").concat(Serialize.tryToJSONString(trait.displayType)!)
```

2024-10-17 23:08 UTC, sisyphusSmiling requested changes
Thanks for the PR, and good call including the `display_type` value. I do wonder if we should only include a serialized `trait.displayType` if it's not `nil`.

2024-10-18 05:42 UTC, bjartek commented
That is probably wise yes

2024-10-22 22:56 UTC, sisyphusSmiling commented
@bjartek in the interest of moving the PR along and make the suggested changes, I'll update to target a feature branch and pick up the PR

2024-10-22 22:58 UTC, merged